# A catppuccin RC for gedit. In beta, specs may change
app_name: gedit
binary_name: gedit
installation:
  location:
    macos: ~/.local/share/gedit/
    linux: ~/.local/share/gedit/
  flavours:
    all:
      default: 
        - themes/
    latte: 
      default: 
        - themes/catppuccin-latte.xml
    frappe:
      default: 
        - themes/catppuccin-frappe.xml
    macchiato:
      default:
        - themes/catppuccin-macchiato.xml
    mocha:
      default:
        - themes/catppuccin-mocha.xml
  to: styles/
  one_flavour: false 
